### ISSUE TITLE
id exceeds the shaping range

### ISSUE THREAD

**Issue by violets007** [rubenlagus/TelegramBots#1021]
Caused by: com.fasterxml.jackson.core.JsonParseException: Numeric value (5011726309) out of range of int
 at [Source: (String)"{"ok":true,"result":[{"update_id":745388191,
"message":{"message_id":13771,"from":{"id":5011726309,"is_bot":false,"first_name":"Tim","last_name":"Zhang","language_code":"zh-hans"},"chat":{"id":5011726309,"first_name":"Tim","last_name":"Zhang","type":"private"},"date":1640518199,"text":"/start","entities":[{"offset":0,"length":6,"type":"bot_command"}]}},{"update_id":745388192,
"message":{"message_id":13781,"from":{"id":1207257557,"is_bot":false,"first_name":"xiaoxuan007","username":"xiaoxuan0071""[truncated 1418 chars]; line: 2, column: 54]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:663)
        at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:869)
        at com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:801)
        at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:645)
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:472)
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:452)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
        ... 18 more

**Comment by zixuan2020** [comment]
version: 

- telegrambots 5.5.0
- jackson-core 2.9.5

**Comment by marcodg97** [comment]
Same problem with telegrambots 5.6.0 

```
Caused by: com.fasterxml.jackson.core.exc.InputCoercionException: Numeric value (5042271810) out of range of int (-2147483648 - 2147483647)
 at [Source: (String)"{"ok":true,"result":[{"update_id":108939829,
"message":{"message_id":4464,"from":{"id":5042271810,"is_bot":false,"first_name":"Julia","username":"XXX","language_code":"it"},"chat":{"id":5042271810,"first_name":"Julia","username":"XXX","type":"private"},"date":1642159565,"text":"/start","entities":[{"offset":0,"length":6,"type":"bot_command"}]}},{"update_id":108939830,
"message":{"message_id":4465,"from":{"id":5042271810,"is_bot":false,"first_name":"Julia","username":"XXX"[truncated 7857 chars]; line: 2, column: 53]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInputCoercion(ParserMinimalBase.java:601) ~[jackson-core-2.10.0.jar:2.10.0]
        at com.fasterxml.jackson.core.base.ParserMinimalBase.reportOverflowInt(ParserMinimalBase.java:570) ~[jackson-core-2.10.0.jar:2.10.0]
        at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:889) ~[jackson-core-2.10.0.jar:2.10.0]
        at com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:802) ~[jackson-core-2.10.0.jar:2.10.0]
        at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:646) ~[jackson-core-2.10.0.jar:2.10.0]
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:472) ~[jackson-databind-2.10.0.jar:2.10.0]
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:452) ~[jackson-databind-2.10.0.jar:2.10.0]
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138) ~[jackson-databind-2.10.0.jar:2.10.0]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.10.0.jar:2.10.0]
        ... 19 common frames omitted
```

**Comment by rubenlagus** [comment]
@zixuan2020 Please update the library, id from User object should be Long

**Comment by violets007** [comment]
Caused by: com.fasterxml.jackson.core.JsonParseException: Numeric value (5359292200) out of range of int
 at [Source: (String)"{"ok":true,"result":[{"update_id":745392698,
"message":{"message_id":221744,"from":{"id":5359292200,"is_bot":false,"first_name":"Pooocky","username":"MillenniumPrototypeMarkII","language_code":"zh-hans"},"chat":{"id":5359292200,"first_name":"Pooocky","username":"MillenniumPrototypeMarkII","type":"private"},"date":1671370796,"text":"/start","entities":[{"offset":0,"length":6,"type":"bot_command"}]}},{"update_id":745392699,
"message":{"message_id":221756,"from":{"id":5359292200,"is_bot":false,"fir"[truncated 619 chars]; line: 2, column: 55]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:663)
        at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:869)
        at com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:801)
        at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:645)
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:472)
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:452)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)

**Comment by violets007** [comment]
I still have this problem with version 6.1.0
