### ISSUE TITLE
400 Bad Request: wrong file identifier/HTTP URL specified

### ISSUE THREAD

**Issue by 123aset** [rubenlagus/TelegramBots#1058]
```
List<InputMedia> medias = new ArrayList<>();
for (String link : linkList) {
    InputMediaVideo inputMediaVideo = new InputMediaVideo();
    inputMediaVideo.setMedia(link);
    medias.add(inputMediaVideo);            
}            
SendMediaGroup sendMediaGroup = new SendMediaGroup();
sendMediaGroup.setChatId(String.valueOf(update.getMessage().getChatId()));
sendMediaGroup.setMedias(medias);
execute(sendMediaGroup);
```
```
Error sending media group: [400] Bad Request: wrong file identifier/HTTP URL specified
	at org.telegram.telegrambots.meta.api.methods.send.SendMediaGroup.deserializeResponse(SendMediaGroup.java:86)
	at org.telegram.telegrambots.bots.DefaultAbsSender.execute(DefaultAbsSender.java:595)
	at Bot.sendFiles(Bot.java:123)
	at Bot.sendStories(Bot.java:86)
	at Bot.processNonCommandUpdate(Bot.java:70)
	at org.telegram.telegrambots.extensions.bots.commandbot.TelegramLongPollingCommandBot.onUpdateReceived(TelegramLongPollingCommandBot.java:70)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.telegram.telegrambots.meta.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27)
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:317)
```

**Comment by rubenlagus** [comment]
That means one of the links you are sending is incorrect, you should use valid ones. It is not an library issue, it is an error from Telegram.
