### ISSUE TITLE
Error getting updates: [401] Unauthorized

### ISSUE THREAD

**Issue by putao0525** [rubenlagus/TelegramBots#1079]
Error getting updates: [401] Unauthorized
	at org.telegram.telegrambots.meta.api.methods.updates.GetUpdates.deserializeResponse(GetUpdates.java:93)
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.getUpdatesFromServer(DefaultBotSession.java:260)
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread$$Lambda$649/226690498.getUpdates(Unknown Source)
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.run(DefaultBotSession.java:189)
2022-06-03 23:59:57.942 - - [ERROR] zixia_bot Telegram Connection DefaultBotSession  Error getting updates: [401] Unauthorized

**Comment by rubenlagus** [comment]
@putao0525 Check your token

**Comment by putao0525** [comment]
How long does the token expire

**Comment by putao0525** [comment]
> @putao0525 Check your token

How long does the token expire
