### ISSUE TITLE
What this problem caused?

### ISSUE THREAD

**Issue by centratelemedia** [rubenlagus/TelegramBots#1114]
add dependencies in pom.xml
```
 <dependency>
            <groupId>org.telegram</groupId>
            <artifactId>telegrambots</artifactId>
            <version>6.1.0</version>
        </dependency>
```

```
Exception in thread "main" java.lang.NoSuchMethodError: 'boolean com.google.common.base.Platform.stringIsNullOrEmpty(java.lang.String)'
        at com.google.common.base.Strings.isNullOrEmpty(Strings.java:73)
        at org.telegram.telegrambots.meta.TelegramBotsApi.validateBotUsernameAndToken(TelegramBotsApi.java:109)
        at org.telegram.telegrambots.meta.TelegramBotsApi.registerBot(TelegramBotsApi.java:61)
        at com.pusatgps.main.Context.init(Context.java:399)
        at com.pusatgps.main.main.main(main.java:75)
```

**Comment by slavino** [comment]
isn't this Guava related https://blog.gradle.org/guava ?

**Comment by centratelemedia** [comment]
@slavino 

i have included guava, still remain error..

```
 <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>31.1-jre</version>
        </dependency>
```

**Comment by slavino** [comment]
https://github.com/google/guava/blob/9c1e5dea4b980202ba003b90fcb64183d42031b3/guava/src/com/google/common/base/Platform.java#L58 

well - not much added value by this check :-/
