### ISSUE TITLE
Connect to api.telegram.org:443 [api.telegram.org/173.244.209.150] failed: Connection timed out: connect

### ISSUE THREAD

**Issue by lee-qinghua** [rubenlagus/TelegramBots#1148]
**Describe the bug**
Connect to api.telegram.org:443 [api.telegram.org/173.244.209.150] failed: Connection timed out: connect

ache.http.client.protocol.RequestAddCookies - CookieSpec selected: default
18:27:39.143 [main] DEBUG org.apache.http.client.protocol.RequestAuthCache - Auth cache not set in the context
18:27:39.145 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://api.telegram.org:443][total available: 0; route allocated: 0 of 2; total allocated: 0 of 100]
18:27:39.159 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {s}->https://api.telegram.org:443][total available: 0; route allocated: 1 of 2; total allocated: 1 of 100]
18:27:39.161 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Opening connection {s}->https://api.telegram.org:443
18:27:40.218 [main] DEBUG org.apache.http.impl.conn.DefaultHttpClientConnectionOperator - Connecting to api.telegram.org/173.244.209.150:443
18:27:40.218 [main] DEBUG org.apache.http.conn.ssl.SSLConnectionSocketFactory - Connecting socket to api.telegram.org/173.244.209.150:443 with timeout 75000
18:28:01.251 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-0: Shutdown connection
18:28:01.251 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Connection discarded
18:28:01.252 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {s}->https://api.telegram.org:443][total available: 0; route allocated: 0 of 2; total allocated: 0 of 100]
Error removing old webhook
	at org.telegram.telegrambots.util.WebhookUtils.clearWebhook(WebhookUtils.java:112)
	at org.telegram.telegrambots.bots.TelegramLongPollingBot.clearWebhook(TelegramLongPollingBot.java:24)
	at org.telegram.telegrambots.meta.TelegramBotsApi.registerBot(TelegramBotsApi.java:65)
	at com.telegram.mybot.BotApp.main(BotApp.java:11)
Caused by: org.telegram.telegrambots.meta.exceptions.TelegramApiException: Unable to execute deleteWebhook method
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:1074)
	at org.telegram.telegrambots.meta.bots.AbsSender.execute(AbsSender.java:64)
	at org.telegram.telegrambots.util.WebhookUtils.clearWebhook(WebhookUtils.java:107)
	... 3 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to api.telegram.org:443 [api.telegram.org/173.244.209.150] failed: Connection timed out: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendHttpPostRequest(DefaultAbsSender.java:1106)
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendMethodRequest(DefaultAbsSender.java:1102)
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:1071)
	... 5 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 16 more

Process finished with exit code 0

**Comment by mrFloony** [comment]
This is not a bug
If you are hosting the bot on a VPS/VDS, try pinging api.telegram.org and trying to telnet to api.telegram.org:443. If it doesn’t, then you need to contact technical support, since at this moment there may be problems with the provider in the data center.
If such a thing comes from a home computer, then check the methods indicated above for access to the API.

**Comment by ksilisk** [comment]
Agree with @mrFloony 
This is not a bug, the problem is on your side. 
Check your internet connection settings.
