### ISSUE TITLE
ERROR DefaultBotSession - Unable to deserialize response

### ISSUE THREAD

**Issue by VanyaNexus** [rubenlagus/TelegramBots#1176]
On start up bot I receive this errors
`17:46:53 [INFO] NEXUSBOT: TG BOT ENABLED2!!!
17:46:53 [INFO] NEXUSBOT: TG BOT ENABLED2!!!
17:46:53 [INFO] NEXUSBOT: TG BOT ENABLED2!!!
17:46:53 [INFO] 17:46:53.665 [NGriefBot Telegram Connection] ERROR org.telegram.telegrambots.updatesreceivers.DefaultBotSession - Unable to deserialize response
org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Unable to deserialize response
	at org.telegram.telegrambots.meta.api.methods.updates.GetUpdates.deserializeResponse(GetUpdates.java:96) ~[NexusBot.jar:?]
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.getUpdatesFromServer(DefaultBotSession.java:260) ~[NexusBot.jar:?]
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.run(DefaultBotSession.java:189) [NexusBot.jar:?]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (2571505618) out of range of int
 at [Source: (StringReader); line: 2, column: 1039]
 at [Source: (StringReader); line: 2, column: 1029] (through reference chain: org.telegram.telegrambots.meta.api.objects.ApiResponse["result"]->java.util.ArrayList[0]->org.telegram.telegrambots.meta.api.objects.Update["message"]->org.telegram.telegrambots.meta.api.objects.Message["video"]->org.telegram.telegrambots.meta.api.objects.Video["file_size"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1704) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:290) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3011) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at org.telegram.telegrambots.meta.api.methods.updates.GetUpdates.deserializeResponse(GetUpdates.java:88) ~[NexusBot.jar:?]
	... 2 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Numeric value (2571505618) out of range of int
 at [Source: (StringReader); line: 2, column: 1039]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:663) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:869) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:801) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:645) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:472) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:452) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136) ~
17:46:53 [INFO] [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3011) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:5a3938a:unknown]
	at org.telegram.telegrambots.meta.api.methods.updates.GetUpdates.deserializeResponse(GetUpdates.java:88) ~[NexusBot.jar:?]
	... 2 more
`
Here is my code Start:
`try {
                TelegramBotsApi botsApi = new TelegramBotsApi(DefaultBotSession.class);
               // tgBotListener = new BotListener();
                botsApi.registerBot(new BotTest());
                System.out.println("NEXUSBOT: TG BOT ENABLED2!!!");
                System.out.println("NEXUSBOT: TG BOT ENABLED2!!!");
                System.out.println("NEXUSBOT: TG BOT ENABLED2!!!");
            } catch (TelegramApiException e) {
                e.printStackTrace();
            }`

Here is BotTest class:
`import org.telegram.telegrambots.bots.TelegramLongPollingBot;
import org.telegram.telegrambots.meta.api.objects.Update;
import ru.vanya.nexusbot.NexusBotPlugin;

public class BotTest extends TelegramLongPollingBot {

    @Override
    public String getBotUsername() {
        return NexusBotPlugin.getTGUsername();
    }

    @Override
    public String getBotToken() {
        return NexusBotPlugin.getTGToken();
    }

    @Override
    public void onUpdateReceived(Update update) {

    }
}
`
What is the problem? This was not the case before. If you remove the registration of the bot, then there is no error at startup.
TelegramBots version is 6.4.0

**Comment by timursergeevichname** [comment]
Are you really to use version 6.4.0 ?

**Comment by VanyaNexus** [comment]
The problem was solved after several reboots and editing the code back and forth, in the end I returned it as it was, I don’t know what it was
