### ISSUE TITLE
SetMyCommands points to an incorrect telegram api path

### ISSUE THREAD

**Issue by vcvitaly** [rubenlagus/TelegramBots#1240]
**Describe the bug**
SetMyCommands points to an incorrect telegram api path, which leads to:
```
Caused by: org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Error executing org.telegram.telegrambots.meta.api.methods.commands.SetMyCommands query: [404] Not Found
	at org.telegram.telegrambots.meta.api.methods.PartialBotApiMethod.deserializeResponseInternal(PartialBotApiMethod.java:54)
	at org.telegram.telegrambots.meta.api.methods.PartialBotApiMethod.deserializeResponse(PartialBotApiMethod.java:34)
	at org.telegram.telegrambots.meta.api.methods.botapimethods.BotApiMethodBoolean.deserializeResponse(BotApiMethodBoolean.java:19)
	at org.telegram.telegrambots.meta.api.methods.botapimethods.BotApiMethodBoolean.deserializeResponse(BotApiMethodBoolean.java:14)
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:1115)
	at com.github.vcvitaly.learnwordsusingphrases.service.TelegramBotService.<init>(TelegramBotService.java:75)
	... 26 common frames omitted
```
The actual command seems to be `setBotCommands`, not `setMyCommands` according to
https://core.telegram.org/method/bots.setBotCommands

**To Reproduce**
1. Try to use `sendApiMethod(setMyCommands)`

**Expected behavior**
Bot commands should be set.

**Comment by Chase22** [comment]
You were looking at the wrong API. The method is SetMyCommands
https://core.telegram.org/bots/api#setmycommands

This is likely caused by a wrong bot token. How are you initialising your bot?

**Comment by rubenlagus** [comment]
Agree with @Chase22 , method is correct as per API specs
