### ISSUE TITLE
Error removing old webhook

### ISSUE THREAD

**Issue by KivenRay** [rubenlagus/TelegramBots#1243]
my code:

           TelegramBotsApi bot = new TelegramBotsApi(DefaultBotSession.class);
            defaultBotService.getOptions().setProxyHost(tgProxyHost);
            defaultBotService.getOptions().setProxyPort(tgProxyPort);
            defaultBotService.getOptions().setProxyType(DefaultBotOptions.ProxyType.SOCKS5);
            bot.registerBot(defaultBotService);

exception message:

org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Error removing old webhook
	at org.telegram.telegrambots.util.WebhookUtils.clearWebhook(WebhookUtils.java:113) ~[telegrambots-6.7.0.jar:na]
	at org.telegram.telegrambots.bots.TelegramLongPollingBot.clearWebhook(TelegramLongPollingBot.java:41) ~[telegrambots-6.7.0.jar:na]
	at org.telegram.telegrambots.meta.TelegramBotsApi.registerBot(TelegramBotsApi.java:65) ~[telegrambots-meta-6.7.0.jar:na]
	at com.ray.telegrambot.register.TelegramBotRegister.defaultBotRegister(TelegramBotRegister.java:56) [classes/:na]
	at com.ray.telegrambot.register.TelegramBotRegister.run(TelegramBotRegister.java:41) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) [spring-boot-2.7.1.jar:2.7.1]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755) [spring-boot-2.7.1.jar:2.7.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.7.1.jar:2.7.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) [spring-boot-2.7.1.jar:2.7.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) [spring-boot-2.7.1.jar:2.7.1]
	at com.ray.telegrambot.TelegramBotApplication.main(TelegramBotApplication.java:13) [classes/:na]
Caused by: org.telegram.telegrambots.meta.exceptions.TelegramApiException: Unable to execute deleteWebhook method
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:1117) ~[telegrambots-6.7.0.jar:na]
	at org.telegram.telegrambots.meta.bots.AbsSender.execute(AbsSender.java:64) ~[telegrambots-meta-6.7.0.jar:na]
	at org.telegram.telegrambots.util.WebhookUtils.clearWebhook(WebhookUtils.java:108) ~[telegrambots-6.7.0.jar:na]
	... 10 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1506) ~[na:1.8.0_333]
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1323) ~[na:1.8.0_333]
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1228) ~[na:1.8.0_333]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412) ~[na:1.8.0_333]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:384) ~[na:1.8.0_333]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.13.jar:4.5.13]
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendHttpPostRequest(DefaultAbsSender.java:1149) ~[telegrambots-6.7.0.jar:na]
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendMethodRequest(DefaultAbsSender.java:1145) ~[telegrambots-6.7.0.jar:na]
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:1114) ~[telegrambots-6.7.0.jar:na]
	... 12 common frames omitted
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:480) ~[na:1.8.0_333]
	at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:469) ~[na:1.8.0_333]
	at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:159) ~[na:1.8.0_333]
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:111) ~[na:1.8.0_333]
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1315) ~[na:1.8.0_333]
	... 29 common frames omitted

**Comment by KivenRay** [comment]
defaultBotService.getOptions().setProxyHost(tgProxyHost);

This method does not seem to set the proxy

**Comment by rubenlagus** [comment]
All of this code is gone now, can you check with new version?
