### ISSUE TITLE
https://api.telegram.org:443: Address already in use: no further information

### ISSUE THREAD

**Issue by skiddgoddamn** [rubenlagus/TelegramBots#1305]
After clicking a few requests /start in the bot | v.6.8.0

SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
╤Å╨╜╨▓. 23, 2024 10:49:50 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {s}->https://api.telegram.org:443: Address already in use: no further information
╤Å╨╜╨▓. 23, 2024 10:49:50 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://api.telegram.org:443
╤Å╨╜╨▓. 23, 2024 10:49:50 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {s}->https://api.telegram.org:443: Address already in use: no further information
╤Å╨╜╨▓. 23, 2024 10:49:50 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://api.telegram.org:443
╤Å╨╜╨▓. 23, 2024 10:49:50 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {s}->https://api.telegram.org:443: Address already in use: no further information
╤Å╨╜╨▓. 23, 2024 10:49:50 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://api.telegram.org:443
org.telegram.telegrambots.meta.exceptions.TelegramApiException: Unable to send photo
        at org.telegram.telegrambots.bots.DefaultAbsSender.execute(DefaultAbsSender.java:277)
        at org.skiddgoddamn.Sender.sendPhotoKeyboard(Sender.java:53)
        at org.skiddgoddamn.trafficformula.onUpdateReceived(trafficformula.java:125)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.telegram.telegrambots.meta.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27)
        at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:312)
Caused by: java.net.BindException: Address already in use: no further information
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.telegram.telegrambots.bots.DefaultAbsSender.sendHttpPostRequest(DefaultAbsSender.java:1149)
        at org.telegram.telegrambots.bots.DefaultAbsSender.execute(DefaultAbsSender.java:275)
        ... 5 more

**Comment by skiddgoddamn** [comment]
CallbackQuery query = update.getCallbackQuery();
        Message message = update.hasCallbackQuery() ? query.getMessage() : update.hasMessage() ? update.getMessage() : null;

**Comment by skiddgoddamn** [comment]
public static void sendPhotoKeyboard(User from, Message message, InlineKeyboardMarkup inlineKeyboardMarkup, boolean clean) throws MalformedURLException {
        SendPhoto sendMessage = new SendPhoto();
        URL url = new URL("photo_link");
        InputFile photo = new InputFile(String.valueOf(url));
        sendMessage.setPhoto(photo);
        sendMessage.setChatId(message.getChatId().toString());
        sendMessage.setReplyMarkup(inlineKeyboardMarkup);
        if (clean) {
            main.cleanup(from);
        }
        try {
            Message sent = new main().execute(sendMessage);
            main.deleteMsg(message.getChatId().toString(), sent.getMessageId());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

**Comment by skiddgoddamn** [comment]
Проблема заключается в том что несколько ботов подключены к одному порту 443. Так как у меня на одном сервере несколько ботов, это вызывало ошибку java.net.BindException .
Есть варианты обойти эту ошибку без использования прокси?

**Comment by rubenlagus** [comment]
Not sure how this can be related to the library considering it is just having issues connecting to TG servers.

That said, feel free to have a look to the new version that changes all of that process all together
