### ISSUE TITLE
SSL Error after migrating from 6.8.0 to 6.9.7.1

### ISSUE THREAD

**Issue by link1107** [rubenlagus/TelegramBots#1352]
**Description**
After migrating from 6.8.0 to 6.9.7.1 at some random moment without any visible reasons bot gets this exception, after which it stops getting updates (looks like update supplier dies after this error):
o.t.t.u.DefaultBotSession                : Remote host terminated the handshake

javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1714) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1514) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426) ~[na:na]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436) ~[httpclient-4.5.14.jar!/:4.5.14]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384) ~[httpclient-4.5.14.jar!/:4.5.14]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.14.jar!/:4.5.14]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.14.jar!/:4.5.14]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.14.jar!/:4.5.14]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.14.jar!/:4.5.14]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.14.jar!/:4.5.14]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.14.jar!/:4.5.14]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.14.jar!/:4.5.14]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.14.jar!/:4.5.14]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.14.jar!/:4.5.14]
	at igorlink.predlozhka.predlozhkabot.customtelegramapi.UpdateSupplierImpl.getUpdates(UpdateSupplierImpl.java:129) ~[!/:1.0]
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.run(DefaultBotSession.java:188) ~[telegrambots-6.9.7.0.jar!/:na]
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:494) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:483) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160) ~[na:na]
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506) ~[na:na]
	... 16 common frames omitted

**Reproducing the bug**
I dont know how to reproduce that. It has appeared after migrating to 6.9.7.1 and I dont see any reasons for this bug.

**Expected behavior**
Not happening.

**Desktop (please complete the following information):**
 - Ubuntu 22.01

**Additional context**
I know that 7.2.0 is already out, but I have a non-commercial huge project with creating and managing a lot of instances of bots, so I have not enough time for this migration at the moment. So any help for figuring this out for 6.9.7.1 would be very appreciated.

**Comment by rubenlagus** [comment]
Doesn't looks related to the library but the TLS versions:  https://stackoverflow.com/questions/28908835/ssl-peer-shut-down-incorrectly-in-java

**Comment by link1107** [comment]
Yeah, I know it looks so, but, there is no such problem on 6.8.0.

In the end I've decided to spend some time and migrated to 7.2.0 last night, fixed that 1 second polling issue I've mentioned in Telegram-chat, and it now runs perfectly without any problems. So issue can be closed now I guess.
