### ISSUE TITLE
CreateInvoiceLink query: [400] Bad Request: STARS_INVOICE_INVALID

### ISSUE THREAD

**Issue by omanhom** [rubenlagus/TelegramBots#1410]
**Describe the bug**
org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Error executing org.telegram.telegrambots.meta.api.methods.invoices.CreateInvoiceLink query: [400] Bad Request: STARS_INVOICE_INVALID
	at org.telegram.telegrambots.meta.api.methods.botapimethods.PartialBotApiMethod.deserializeResponseInternal(PartialBotApiMethod.java:61)
	at org.telegram.telegrambots.meta.api.methods.botapimethods.PartialBotApiMethod.deserializeResponse(PartialBotApiMethod.java:41)
	at org.telegram.telegrambots.meta.api.methods.invoices.CreateInvoiceLink.deserializeResponse(CreateInvoiceLink.java:238)
	at org.telegram.telegrambots.meta.api.methods.invoices.CreateInvoiceLink.deserializeResponse(CreateInvoiceLink.java:29)
	at org.telegram.telegrambots.client.okhttp.OkHttpFutureCallback.onResponse(OkHttpFutureCallback.java:35)

**To Reproduce**
OkHttpTelegramClient telegramClient = new OkHttpTelegramClient("your token");
        CreateInvoiceLinkBuilder createInvoiceLinkBuilder = CreateInvoiceLink.builder();
        createInvoiceLinkBuilder.title("recharge stars");
        createInvoiceLinkBuilder.description("recharge stars desc");
        createInvoiceLinkBuilder.payload("{}");
        createInvoiceLinkBuilder.currency("XTR");
        createInvoiceLinkBuilder.providerToken("");
        Collection<LabeledPrice> prices =  Lists.newArrayList(new LabeledPrice("价格1", 1),new LabeledPrice("价格2", 2));
        createInvoiceLinkBuilder.prices(prices);
        CreateInvoiceLink createInvoiceLink = createInvoiceLinkBuilder.build();
        String url = telegramClient.execute(createInvoiceLink);

**Comment by omanhom** [comment]
prices must one item

**Comment by omanhom** [comment]
prices must one item

**Comment by rubenlagus** [comment]
what if you try  to use a different payload? something like "1234"? 

Basically that error is the server saying that something in the message message is wrong

**Comment by lll-Death-lll** [comment]
Same issue, with different library. Doesn't work with any payload that I try to set. Guess something is wrong on the telegram level

**Comment by omanhom** [comment]
XTR price must one item

**Comment by Sheharyar566** [comment]
Providing a single item to prices fixed the issue.
