### ISSUE TITLE
The bot initialization process fails with a 401 Response Status

### ISSUE THREAD

**Issue by Floy3DDD** [rubenlagus/TelegramBots#1418]
Actual result:

`Exception in thread "main" Error removing old webhook
        at org.telegram.telegrambots.util.WebhookUtils.clearWebhook(WebhookUtils.java:113)
        at org.telegram.telegrambots.bots.TelegramLongPollingBot.clearWebhook(TelegramLongPollingBot.java:41)
        at org.telegram.telegrambots.meta.TelegramBotsApi.registerBot(TelegramBotsApi.java:65)
        at com.theawarenessday.Main.main(Main.java:27)
Caused by: Error executing org.telegram.telegrambots.meta.api.methods.updates.DeleteWebhook query: [401] Unauthorized
        at org.telegram.telegrambots.meta.api.methods.PartialBotApiMethod.deserializeResponseInternal(PartialBotApiMethod.java:54)
        at org.telegram.telegrambots.meta.api.methods.PartialBotApiMethod.deserializeResponse(PartialBotApiMethod.java:34)
        at org.telegram.telegrambots.meta.api.methods.botapimethods.BotApiMethodBoolean.deserializeResponse(BotApiMethodBoolean.java:19)
        at org.telegram.telegrambots.meta.api.methods.botapimethods.BotApiMethodBoolean.deserializeResponse(BotApiMethodBoolean.java:14)
        at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:1182)
        at org.telegram.telegrambots.meta.bots.AbsSender.execute(AbsSender.java:61)
        at org.telegram.telegrambots.util.WebhookUtils.clearWebhook(WebhookUtils.java:108)
        ... 3 more`

Version of the lib: 'org.telegram:telegrambots:6.9.7.1'

Steps to reproduce:
1. Logged in to the telegram test environment.
2. Created a new bot via https://t.me/botfather
3. Emited the token
4. Initialization of the bot according to the documentation [https://core.telegram.org/bots/tutorial](url) gives results with the stack trace described above

Note: with production credentials, the initialization process passes correctly.

Will be glad to get any feedback about the issue, thank you in advance!

**Comment by Floy3DDD** [comment]
Wrong configuration
