### ISSUE TITLE
stars payment error:PAYMENT_PROVIDER_INVALID

### ISSUE THREAD

**Issue by zkywalker** [rubenlagus/TelegramBots#1445]
version:7.10.0
code:
`
val build = SendInvoice.builder()
                    .chatId(it.chatId())
                    .title("test")
                    .description("test")
                    .payload("test")
                    .currency("TXR")
                    .providerToken("")
                    .price(LabeledPrice("Label", 100))
                    .startParameter("test")
                    .build()
                silent.execute(build)
`
log:
`
 Could not execute bot API method

org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Error executing org.telegram.telegrambots.meta.api.methods.invoices.SendInvoice query: [400] Bad Request: PAYMENT_PROVIDER_INVALID
        at org.telegram.telegrambots.meta.api.methods.botapimethods.PartialBotApiMethod.deserializeResponseInternal(PartialBotApiMethod.java:61) ~[telegrambots-meta-7.10.0.jar!/:na]
        at org.telegram.telegrambots.meta.api.methods.botapimethods.PartialBotApiMethod.deserializeResponse(PartialBotApiMethod.java:41) ~[telegrambots-meta-7.10.0.jar!/:na]
        at org.telegram.telegrambots.meta.api.methods.botapimethods.BotApiMethodMessage.deserializeResponse(BotApiMethodMessage.java:24) ~[telegrambots-meta-7.10.0.jar!/:na]
        at org.telegram.telegrambots.meta.api.methods.botapimethods.BotApiMethodMessage.deserializeResponse(BotApiMethodMessage.java:17) ~[telegrambots-meta-7.10.0.jar!/:na]
        at org.telegram.telegrambots.client.okhttp.OkHttpFutureCallback.onResponse(OkHttpFutureCallback.java:35) ~[telegrambots-client-7.10.0.jar!/:na]
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) ~[okhttp-4.12.0.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
`

**Comment by holly-gnolly** [comment]
+1

**Comment by rubenlagus** [comment]
Have you tried not setting provider at all?

**Comment by logesh2496** [comment]
+1
tested with both setting the providerToken as empty string and without the property itself. same error

**Comment by rubenlagus** [comment]
Tested it myself right now with below request, working fine:

```
SendInvoice sendInvoice = SendInvoice
                .builder()
                .chatId(callbackQuery.getMessage().getChatId())
                .title("title")
                .description("Description ")
                .payload(callbackQuery.getId() + "-" + System.currentTimeMillis())
                .currency("XTR")
                .price(LabeledPrice
                        .builder()
                        .label("Price")
                        .amount(100)
                        .build()
                )
                .build();
```

**Comment by holly-gnolly** [comment]
I found the problem by deep debugging, it turned out that due to the transitive dependencies of spring boot, the code used an old version of jackson lib, but the problem was that the exception was swallowed and did not get anywhere.

**Comment by zkywalker** [comment]
It seems the builder does not work in Kotlin code. It works for me like this:

`
                val createInvoiceLinkBuilder = SendInvoice.builder()
                createInvoiceLinkBuilder.chatId(it.chatId())
                createInvoiceLinkBuilder.title("测试星星支付")
                createInvoiceLinkBuilder.description("测试星星支付 desc")
                createInvoiceLinkBuilder.payload("{}")
                createInvoiceLinkBuilder.currency("XTR")
                createInvoiceLinkBuilder.providerToken("")
                val prices = Lists.newArrayList(LabeledPrice("价格1", 1))
                createInvoiceLinkBuilder.prices(prices)
                val createInvoiceLink = createInvoiceLinkBuilder.build()
                silent.execute(createInvoiceLink)
`
