### ISSUE TITLE
AbilityBot: Could not retrieve originating user from update (ChatBoostUpdated)

### ISSUE THREAD

**Issue by ekomrak** [rubenlagus/TelegramBots#1463]
Ability Bot stopped working with the following exception (I added additional logging) during ChatBoostUpdated operations:
 
```
[23:09:55] ERROR: java.lang.IllegalStateException: Could not retrieve originating user from update: Update(updateId=123456789, message=null, inlineQuery=null, chosenInlineQuery=null, callbackQuery=null, editedMessage=null, channelPost=null, editedChannelPost=null, shippingQuery=null, preCheckoutQuery=null, poll=null, pollAnswer=null, myChatMember=null, chatMember=null, chatJoinRequest=null, messageReaction=null, messageReactionCount=null, chatBoost=ChatBoostUpdated(chat=Chat(id=-1111127333111, type=supergroup, title=Title, firstName=null, lastName=null, userName=Name1, isForum=null), boost=ChatBoost(boostId=ef6d16fd222b9d6df04486d40b607cd2, addDate=1733335794, expirationDate=1734183113, source=ChatBoostSourcePremium(source=premium, user=User(id=9999999999, firstName=Name, isBot=false, lastName=null, userName=Name22, languageCode=null, canJoinGroups=null, canReadAllGroupMessages=null, supportInlineQueries=null, isPremium=true, addedToAttachmentMenu=null, canConnectToBusiness=null, hasMainWebApp=null)))), removedChatBoost=null, businessConnection=null, businessMessage=null, editedBuinessMessage=null, deletedBusinessMessages=null, paidMediaPurchased=null)
	at org.telegram.telegrambots.abilitybots.api.util.AbilityUtils.getUserElseThrow(AbilityUtils.java:104)
	at org.telegram.telegrambots.abilitybots.api.util.AbilityUtils.getUser(AbilityUtils.java:61)
	at org.telegram.telegrambots.abilitybots.api.bot.BaseAbilityBot.checkBlacklist(BaseAbilityBot.java:476)
```

The same issue will be for the ChatBoostRemoved case.

Version: 7.x, 8.x

**Comment by Dramex** [comment]
Opened #1584 with branches added to `AbilityUtils.getUser` and `AbilityUtils.getChatId` for both `chatBoost` and `removedChatBoost` updates. Same shape as the channel-posts fix in #1550 — new `HAS_CHAT_BOOST` / `HAS_REMOVED_CHAT_BOOST` flags, pattern-matched `ChatBoostSource` subtypes, anonymous giveaways fall back to `EMPTY_USER`. Five regression tests added.
