### ISSUE TITLE
Bot crashes

### ISSUE THREAD

**Issue by felixletsplayYT** [rubenlagus/TelegramBots#277]
Exception in thread "main" com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for org.telegram.telegrambots.generics.BotSession was bound.
  while locating org.telegram.telegrambots.generics.BotSession

1 error
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1045)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1004)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at org.telegram.telegrambots.ApiContext.getInstance(ApiContext.java:25)
	at org.telegram.telegrambots.TelegramBotsApi.registerBot(TelegramBotsApi.java:121)
	at de.felix.telegrammbot.Main.<init>(Main.java:22)
	at de.felix.telegrammbot.Starter.main(Starter.java:10)

**Comment by felixletsplayYT** [comment]
Forgot ApiContext init
