### ISSUE TITLE
java.net.SocketException: Socket is not connected:

### ISSUE THREAD

**Issue by nickolson77** [rubenlagus/TelegramBots#288]
Hi, I'm using below code and got error. Maybe problem in proxy settings?
```
public class SimpleBot extends TelegramLongPollingBot {
 
	public static void main(String[] args) {
		ApiContextInitializer.init();
		TelegramBotsApi telegramBotsApi = new TelegramBotsApi();
	    
		try {                    
                    telegramBotsApi.registerBot(new SimpleBot());
		} catch (TelegramApiException e) {
			e.printStackTrace();
		}
	}
```
```
Retrying request to {s}->https://api.telegram.org:443
org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error executing setWebook method
	at org.telegram.telegrambots.bots.TelegramLongPollingBot.clearWebhook(TelegramLongPollingBot.java:56)
	at org.telegram.telegrambots.TelegramBotsApi.registerBot(TelegramBotsApi.java:120)
	at menu.SimpleBot.main(SimpleBot.java:18)
Caused by: java.net.SocketException: Socket is not connected: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:339)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.telegram.telegrambots.bots.TelegramLongPollingBot.clearWebhook(TelegramLongPollingBot.java:44)
```

**Comment by rubenlagus** [comment]
Maybe you can try to configure a RequestConfig with the settings of your proxy and provide it in the BotOptions? https://github.com/rubenlagus/TelegramBots/blob/master/telegrambots/src/main/java/org/telegram/telegrambots/bots/DefaultBotOptions.java#L69

**Comment by nickolson77** [comment]
Hi, thanks for reply. The same error with following code:

```
public class SimpleBot extends TelegramLongPollingBot {
 
	public static void main(String[] args) {
            
            HttpHost proxy = new HttpHost("10.10.100.2", 3128, "https");
            RequestConfig config = RequestConfig.custom().setProxy(proxy).build();
	    
            
	    DefaultBotOptions opt = new DefaultBotOptions();
            opt.setRequestConfig(config);
            
            ApiContextInitializer.init();
            TelegramBotsApi telegramBotsApi = new TelegramBotsApi();
	    
       
            try {                    
                telegramBotsApi.registerBot(new SimpleBot());
            } catch (TelegramApiException e) {
                    e.printStackTrace();
            }
	}
```

**Comment by stefan-kolb** [comment]
> Method "sendMessage(sendMessage)" is deprecated. (@deprecated public final Message sendMessage(SendMessage p1) { }) Are there alternatives ?

Alternatives are `#execute`

**Comment by nickolson77** [comment]
> Alternatives are #execute
Sorry, not clear for me =) What do you mean saying #execute ?

**Comment by stefan-kolb** [comment]
@nickolson77 The new method is called `execute` instead of `sendMessage`.

**Comment by nickolson77** [comment]
Ok, thanks =) It works!

ps
Now I'm trying to implement following for my bot and can't find any examples:
1) User subscribe to my bot
2) Bot send message to all subscribed users

Could you help me?

**Comment by stefan-kolb** [comment]
See https://github.com/rubenlagus/TelegramBots/wiki/Getting-Started.
Check for `/start` message. 
For your second question just send a message to all your users via chatIDs (throttle sending to ~30msg/second!).
