### ISSUE TITLE
Error during connection to telegram bot ERROR 1928 --- [gram Connection] Telegram Bots Api : BOTSESSION

### ISSUE THREAD

**Issue by dinarAkv** [rubenlagus/TelegramBots#306]
Hello,  yesterday my program (bot) work well, but today I every time after run apllication get next erro: 

ERROR 1928 --- [gram Connection] Telegram Bots Api : BOTSESSION

org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error getting updates at org.telegram.telegrambots.api.methods.updates.GetUpdates.deserializeResponse(GetUpdates.java:119) ~[telegrambots-meta-3.3.jar:na]
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.run(DefaultBotSession.java:203) ~[telegrambots-3.3.jar:na]

What wrong with my application or there is some thing wrong with telegram api ?

I tried other stable commits in my application and get the same error.

**Comment by dinarAkv** [comment]
Now everithing work well. I think this exception was temporary on telegram api side. Issue can be closed.

**Comment by dinarAkv** [comment]
I found problem. The problem was that I try to run 2 servers that address to the same telegram bot at the same time. The firest was remote server and second was local. There is allow address to telegram bot only for one server at the same time.
