### ISSUE TITLE
Error while deleting message

### ISSUE THREAD

**Issue by Schmiddinger** [rubenlagus/TelegramBots#335]
Hi Community, 
I tried to delete a message:
`DeleteMessage deleteMessage = new DeleteMessage();
deleteMessage.setChatId(update.getMessage().getChatId().toString());
deleteMessage.setMessageId(update.getMessage().getMessageId());`

and I get this error:

`org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error editing message caption: [400] Bad Request: message can't be deleted
	at org.telegram.telegrambots.api.methods.updatingmessages.DeleteMessage.deserializeResponse(DeleteMessage.java:88)
	at org.telegram.telegrambots.api.methods.updatingmessages.DeleteMessage.deserializeResponse(DeleteMessage.java:25)
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:627)
	at org.telegram.telegrambots.bots.AbsSender.deleteMessage(AbsSender.java:307)
	at eu.schmiddinger.telegram.SmdBOT.SchmiddiBOT.onUpdateReceived(SchmiddiBOT.java:35)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.telegram.telegrambots.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27)
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:301)`

I'm trying to delete a message from a user (me) in a private chat

**Comment by rubenlagus** [comment]
The `caption` error comes from [this line](https://github.com/rubenlagus/TelegramBots/blob/master/telegrambots-meta/src/main/java/org/telegram/telegrambots/api/methods/updatingmessages/DeleteMessage.java#L88), I'll fix it. 

But it shouldn't have any relation with your error. Are you maybe trying to delete an old message?

**Comment by Schmiddinger** [comment]
I'm trying to create a mute bot.
If a username is in a ArrayList, the message should be deleted automatically.

**Comment by rubenlagus** [comment]
Your bot should have enough permissions to do it. In addition, remember that only recent messages (up to 48h) can be deleted.

**Comment by Schmiddinger** [comment]
Error keeps alive... @rubenlagus
