### ISSUE TITLE
Starting the bot in Webhook mode results in [429] Too Many Requests: retry after 1

### ISSUE THREAD

**Issue by pouraghajan** [rubenlagus/TelegramBots#348]
Hi,

I'm having a very troubling time dealing with WebHook mode, launching my telegram bot.
After spending a great portion of time figuring out how to generate a self signed certificate and configure the webhook mode in my code (BuildVars Class), finally I got to this stage of running the bot.
Unfortunately, immediately after I run the jar file (in which my whole project is included), below exception is being thrown and no request reaches to the back-end afterwards.
I appreciate if anyone (who might faced the same issue) could help me get over with this annoying problem!!

`Dec 12, 2017 9:22:27 AM org.glassfish.grizzly.http.server.NetworkListener start
INFO: Started listener bound to [x.x.x.x:8443]
Dec 12, 2017 9:22:27 AM org.glassfish.grizzly.http.server.HttpServer start
INFO: [HttpServer] Started.
Dec 12, 2017 9:22:29 AM org.telegram.telegrambots.logging.BotLogger severe
SEVERE: MAIN
org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error setting webhook: [429] Too Many Requests: retry after 1
        at org.telegram.telegrambots.bots.TelegramWebhookBot.setWebhook(TelegramWebhookBot.java:74)
        at org.telegram.telegrambots.TelegramBotsApi.registerBot(TelegramBotsApi.java:136)
        at org.telegram.Main.main(Main.java:38)

Dec 12, 2017 9:22:29 AM org.telegram.telegrambots.logging.BotLogger severe
SEVERE: MAIN
org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error setting webhook: [429] Too Many Requests: retry after 1
        at org.telegram.telegrambots.bots.TelegramWebhookBot.setWebhook(TelegramWebhookBot.java:74)
        at org.telegram.telegrambots.TelegramBotsApi.registerBot(TelegramBotsApi.java:136)
        at org.telegram.Main.main(Main.java:38)`

**Comment by pouraghajan** [comment]
Hi all,

It was actually my own fault. based on the default code sample provided by this repository the LongPolling bot is being registered anyway (regardless of your choice to use WebHook or LongPolling).
so remember to comment (or remove the registerBot() line in the webhook (selfsigned and noSelfSigned) part of the code in the Main.java class.

`public static void main(String[] args) {
        BotLogger.setLevel(Level.ALL);
        BotLogger.registerLogger(new ConsoleHandler());
        try {
            BotLogger.registerLogger(new BotsFileHandler());
        } catch (IOException e) {
            BotLogger.severe(LOGTAG, e);
        }

        try {
            ApiContextInitializer.init();
            TelegramBotsApi telegramBotsApi = createTelegramBotsApi();
            try {
                // Register long polling bots. They work regardless type of TelegramBotsApi we are creating
                **telegramBotsApi.registerBot(new YourBotHandler());**
            } catch (TelegramApiException e) {
                BotLogger.error(LOGTAG, e);
            }
        } catch (Exception e) {
            BotLogger.error(LOGTAG, e);
        }
    }

    private static TelegramBotsApi createTelegramBotsApi() throws TelegramApiException {
        TelegramBotsApi telegramBotsApi;
        if (!BuildVars.useWebHook) {
            // Default (long polling only)
            telegramBotsApi = createLongPollingTelegramBotsApi();
        } else if (!BuildVars.pathToCertificatePublicKey.isEmpty()) {
            // Filled a path to a pem file ? looks like you're going for the self signed option then, invoke with store and pem file to supply.
            telegramBotsApi = createSelfSignedTelegramBotsApi();
            **//telegramBotsApi.registerBot(new YourBotHandler());**
        } else {
            // Non self signed, make sure you've added private/public and if needed intermediate to your cert-store.
            telegramBotsApi = createNoSelfSignedTelegramBotsApi();
            **//telegramBotsApi.registerBot(new YourBotHandler());**
        }
        return telegramBotsApi;
    }`
