### ISSUE TITLE
after packing in jar prog stop working

### ISSUE THREAD

**Issue by Wizard1209** [rubenlagus/TelegramBots#358]
IDEA 2017 + Maven + Java 8.151
Project runs well from IDE, but after building APK using jar gives this Stack Trace
`java.lang.NoClassDefFoundError: org/telegram/telegrambots/exceptions/TelegramApiException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.telegram.telegrambots.exceptions.TelegramApiException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" `

**Comment by dzienskaj** [comment]
Hey, i have the same problem. Did you figure it out?

**Comment by SAYIHEM** [comment]
Having same problem with an equal setup.

**Comment by alexoley** [comment]
Hi everyone! How did you solved this problem?

**Comment by ModSeven** [comment]
same problem please help

**Comment by rubenlagus** [comment]
@Wizard1209 Building APK? Are you using it in Android? This library use Java8, maybe some parts are not working on Android.

**Comment by rubenlagus** [comment]
Closing due inactivity

**Comment by alexoley** [comment]
I get this error while trying to build application on desktop using Maven.

**Comment by rubenlagus** [comment]
Then, why are you trying to build an APK?

**Comment by alexoley** [comment]
No, I try to build application using
`mvn package`
but when run
`java -jar hello-world-0.1.0.jar` 
I get such output
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/telegram/telegrambots/exceptions/TelegramApiException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.telegram.telegrambots.exceptions.TelegramApiException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```
I put the project in the repository:
[https://github.com/alexoley/HelpBotMaven](url)

**Comment by rubenlagus** [comment]
@alexoley Try to use: `mvn clean compile assembly:single`, it should work

**Comment by davidtowers** [comment]
How did you manage to solve it?
