### ISSUE TITLE
Exception on initial connection

### ISSUE THREAD

**Issue by wasnertobias** [rubenlagus/TelegramBots#367]
Sadly I am not able to reproduce that Exception, but it happenend when I first sent a gif to my newly setup bot (not my only one) and then tried to start the bot. I am using the TelegramLongPollingBot-API. 

> Exception in thread "PrivatePingBot Telegram Connection" java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonGenerator.writeStartObject(Ljava/lang/Object;)V
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:151)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:292)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3681)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3057)
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.getUpdatesFromServer(DefaultBotSession.java:242)
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.run(DefaultBotSession.java:187)

It is somehow not bound to the certain bot (token/name). Any guesses?

Update: This seems to happen for me only when adding a certain dependency:
> 
        <dependency>
            <groupId>io.parallec</groupId>
            <artifactId>parallec-core</artifactId>
            <version>0.10.6</version>
        </dependency>

**Comment by rubenlagus** [comment]
Can't know, maybe that dependency is adding something that conflict with the API?

**Comment by Mattue** [comment]
I can say I have the same issue after adding dropbox dependency.

```
<dependency>
    <groupId>com.dropbox.core</groupId>
    <artifactId>dropbox-core-sdk</artifactId>
    <version>3.0.6</version>
</dependency>
```

**Comment by rubenlagus** [comment]
@Mattue and @wasnertobias Any news regarding the conflicts?

**Comment by wasnertobias** [comment]
Not for me.

Ruben Bermudez <notifications@github.com> schrieb am Sa., 21. Apr. 2018,
11:50:
