### ISSUE TITLE
Error when trying to send message through AbsSender

### ISSUE THREAD

**Issue by ilya-gr** [rubenlagus/TelegramBots#432]
I start my bot and it recieves updates, but when I want to send message, it throws an exception:

java.lang.reflect.UndeclaredThrowableException: null
	at com.ibgry.stat78.service.RegistrationService$$EnhancerBySpringCGLIB$$6f2a4d6a.registration(<generated>) ~[classes!/:0.0.1-SNAPSHOT]
	at com.ibgry.stat78.bot.Bot.onUpdateReceived(Bot.java:61) ~[classes!/:0.0.1-SNAPSHOT]
	at java.util.ArrayList.forEach(Unknown Source) ~[na:1.8.0_161]
	at org.telegram.telegrambots.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27) ~[telegrambots-meta-3.6.jar!/:na]
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:311) ~[telegrambots-3.6.jar!/:na]
Caused by: org.telegram.telegrambots.exceptions.TelegramApiException: Unable to execute sendmessage method
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:692) ~[telegrambots-3.6.jar!/:na]
	at org.telegram.telegrambots.bots.AbsSender.execute(AbsSender.java:53) ~[telegrambots-meta-3.6.jar!/:na]
	at org.telegram.telegrambots.bots.AbsSender$$FastClassBySpringCGLIB$$d155e2a3.invoke(<generated>) ~[telegrambots-meta-3.6.jar!/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685) ~[spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.telegram.telegrambots.bots.AbsSender$$EnhancerBySpringCGLIB$$40369b7a.execute(<generated>) ~[telegrambots-meta-3.6.jar!/:na]
	at com.ibgry.stat78.service.RegistrationService.registration(RegistrationService.java:43) ~[classes!/:0.0.1-SNAPSHOT]
	at com.ibgry.stat78.service.RegistrationService$$FastClassBySpringCGLIB$$7399d1d0.invoke(<generated>) ~[classes!/:0.0.1-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747) ~[spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	... 5 common frames omitted
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to api.telegram.org:443 [api.telegram.org/149.154.167.220] failed: Connection refused: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159) ~[httpclient-4.5.5.jar!/:4.5.5]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373) ~[httpclient-4.5.5.jar!/:4.5.5]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[httpclient-4.5.5.jar!/:4.5.5]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.5.jar!/:4.5.5]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.5.jar!/:4.5.5]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.5.jar!/:4.5.5]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[httpclient-4.5.5.jar!/:4.5.5]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.5.jar!/:4.5.5]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.5.jar!/:4.5.5]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.5.jar!/:4.5.5]
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendHttpPostRequest(DefaultAbsSender.java:738) ~[telegrambots-3.6.jar!/:na]
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendMethodRequest(DefaultAbsSender.java:734) ~[telegrambots-3.6.jar!/:na]
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:689) ~[telegrambots-3.6.jar!/:na]
	... 19 common frames omitted
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[na:1.8.0_161]
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[na:1.8.0_161]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:1.8.0_161]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:1.8.0_161]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_161]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_161]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[na:1.8.0_161]
	at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_161]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:339) ~[httpclient-4.5.5.jar!/:4.5.5]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.5.jar!/:4.5.5]
	... 31 common frames omitted

How can i fix this?

**Comment by liyaxc** [comment]
@ilya-gr where can I add IP to a white-list? have the same issue

**Comment by bvn13** [comment]
@liyaxc you are not allowed to do this. use proxy and vpn so.
