### ISSUE TITLE
"TelegramApiRequestException: Error executing setWebook method" when trying to register a bot

### ISSUE THREAD

**Issue by tghns** [rubenlagus/TelegramBots#439]
Maybe it's somehow connected with my government trying to ban telegram, because a month ago my bot worked.
Is there any way to fix that?

My code: 

```
public static void main(String args[]) {
        TelegramBotsApi telegramBotsApi = new TelegramBotsApi();
        TelegramBot telegramService = new TelegramBot();

        try {
            telegramBotsApi.registerBot(telegramService);
        } catch (TelegramApiRequestException e) {
            e.printStackTrace();
        }

    }
```

Output:

org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error executing setWebook method
	at org.telegram.telegrambots.bots.TelegramLongPollingBot.clearWebhook(TelegramLongPollingBot.java:55)
	at org.telegram.telegrambots.TelegramBotsApi.registerBot(TelegramBotsApi.java:120)
	at main.Main.main(Main.java:30)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to api.telegram.org:443 [api.telegram.org/81.200.2.238] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.telegram.telegrambots.bots.TelegramLongPollingBot.clearWebhook(TelegramLongPollingBot.java:43)
	... 2 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:339)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 12 more

Process finished with exit code 0

**Comment by carlopantaleo** [comment]
Yes indeed. I used to run my bot on a Russian server and two days ago it stopped working.
Since this issue is not related to this library, there's no easy fix. However you might:
- send requests to api.telegram.org through a (non Russian) proxy or an SSH tunnel,
- use a (non Russian) VPN on your machine,
- consider moving your bot to a server outside Russia.

Hope it helps...

**Comment by tghns** [comment]
@carlopantaleo Thanks for your reply.
Could you please describe how can I apply your first method (sending requests through a proxy)?

**Comment by carlopantaleo** [comment]
As far as I know, you should do something like this (not tested, my bot is more complex than this):

```java
ApiContextInitializer.init();
TelegramLongPollingBot bot = new YourBot();

String proxyHost = "1.2.3.4";
int proxyPort = 1234;
int timeout = 75 * 1000;

RequestConfig requestConfig = RequestConfig.custom()
        .setProxy(new HttpHost(proxyHost, proxyPort)
        .setSocketTimeout(timeout)
        .setConnectionRequestTimeout(timeout)
        .setConnectTimeout(timeout)
        .build();
bot.getOptions().setRequestConfig(requestConfig);

TelegramBotsApi botsApi = new TelegramBotsApi();
botsApi.registerBot(bot);
```
with `proxyHost` and `proxyPort` your proxy host and port.
However, as of now, I haven't got any luck making it work...

**Comment by bvn13** [comment]
@tghns for using http proxy check my pull request and vote it if it helps you
https://github.com/rubenlagus/TelegramBots/pull/435

**Comment by bvn13** [comment]
@carlopantaleo check it https://github.com/rubenlagus/TelegramBots/pull/435

**Comment by tghns** [comment]
@bvn13 Thanks. It works now

**Comment by deft1991** [comment]
> * send requests to api.telegram.org through a (non Russian) proxy or an SSH tunnel,

yeah man it`s great. you realy help me
