### ISSUE TITLE
removing old webhook

### ISSUE THREAD

**Issue by dygy** [rubenlagus/TelegramBots#442]
so I do long polling bot with 3.6.1 
not even hello world one
my bot class is 

```
public class My_Bot extends TelegramLongPollingBot {
    @Override
public void onUpdateReceived(Update update) {
}
    @Override
    public String getBotUsername() {
        return "";
    }
    @Override
    public String getBotToken() {
        return "";        
    }
}

```
and my main 

```
public class Main {
    public static void main(String[] args) {
        try {
            ApiContextInitializer.init();
            TelegramBotsApi botsApi = new TelegramBotsApi();
            botsApi.registerBot((LongPollingBot) new My_Bot());
        } catch (TelegramApiException e) {
            e.printStackTrace();
        }
    }
}
```

say to run and get

```
org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error removing old webhook
	at org.telegram.telegrambots.bots.TelegramLongPollingBot.clearWebhook(TelegramLongPollingBot.java:32)
	at org.telegram.telegrambots.TelegramBotsApi.registerBot(TelegramBotsApi.java:120)
	at Main.main(Main.java:14)
Caused by: org.telegram.telegrambots.exceptions.TelegramApiException: Unable to execute deleteWebhook method
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:691)
	at org.telegram.telegrambots.bots.AbsSender.execute(AbsSender.java:53)
	at org.telegram.telegrambots.bots.TelegramLongPollingBot.clearWebhook(TelegramLongPollingBot.java:27)

```

It all means???

**Comment by dygy** [comment]
not been so negative, going to try ability bot. 
so main is 
public class Main {
private static String botToken ="";
    private static String botName ="";
    public static void main(String[] args) {
        ApiContextInitializer.init();
        TelegramBotsApi botsApi = new TelegramBotsApi();
        DefaultBotOptions botOptions = ApiContext.getInstance(DefaultBotOptions.class);
        try {
            My_Bot AbilityBot = new My_Bot(botToken,botName,botOptions);
            botsApi.registerBot(AbilityBot);

        } catch (TelegramApiException e) {
            e.printStackTrace();
        }
    }
}

and my  bot class is 

public class My_Bot extends AbilityBot {

    protected My_Bot(String botToken, String botUsername,
                        DefaultBotOptions botOptions) {
        super(botToken, botUsername, botOptions);
    }

    @Override
    public int creatorId() {
        return 12345678;
    }
    public Ability sayHelloWorld() {
        return Ability
                .builder()
                .name("hello")
                .info("says hello world!")
                .locality(ALL)
                .privacy(PUBLIC)
                .action(ctx -> silent.send("Hello world!", ctx.chatId()))
                .build();
    }
}

getting  same

org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error removing old webhook
	at org.telegram.telegrambots.bots.TelegramLongPollingBot.clearWebhook(TelegramLongPollingBot.java:32)
	at org.telegram.telegrambots.TelegramBotsApi.registerBot(TelegramBotsApi.java:120)
	at Main.main(Main.java:14)

what it means also???

**Comment by dygy** [comment]
my gradle is
version '1.0-SNAPSHOT'

apply plugin: 'java'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    compile group: 'org.telegram', name: 'telegrambots-abilities', version: '3.6.1'
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile group: 'org.telegram', name: 'telegrambots', version: '3.6.1'


}

**Comment by dygy** [comment]
and if somebody can tell me, do I need to try a webhook bot, or I will face same? :laughing:

**Comment by rubenlagus** [comment]
@dygy It is a problem executing deleteWebhook method, in a full stacktrace, there should be a new cause for this exception:

`Caused by: org.telegram.telegrambots.exceptions.TelegramApiException: Unable to execute deleteWebhook method`

can you get it?

**Comment by dygy** [comment]
'org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error removing old webhook
	at org.telegram.telegrambots.bots.TelegramLongPollingBot.clearWebhook(TelegramLongPollingBot.java:32)
	at org.telegram.telegrambots.TelegramBotsApi.registerBot(TelegramBotsApi.java:120)
	at Main.main(Main.java:13)
Caused by: org.telegram.telegrambots.exceptions.TelegramApiException: Unable to execute deleteWebhook method
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:691)
	at org.telegram.telegrambots.bots.AbsSender.execute(AbsSender.java:53)
	at org.telegram.telegrambots.bots.TelegramLongPollingBot.clearWebhook(TelegramLongPollingBot.java:27)
	... 2 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to api.telegram.org:443 [api.telegram.org/149.154.167.220] failed: Connection timed out: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendHttpPostRequest(DefaultAbsSender.java:737)
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendMethodRequest(DefaultAbsSender.java:733)
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:688)
	... 4 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:339)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 16 more
Exception in thread "main" java.lang.NullPointerException
	at Main.mash(Main.java:23)
	at Main.crunch(Main.java:20)
	at Main.main(Main.java:16)

'Process finished with exit code 1
Not sure how to see "more" in IDEA or anywhere at this moment.
Will past if i will get how.

**Comment by rubenlagus** [comment]
`Caused by: java.net.ConnectException: Connection timed out: connect`

This error means that there is a problem connecting to Telegram servers from yours.  More exactly to reach `[api.telegram.org/149.154.167.220]`, maybe you can check if there is something preventing it to reach (firewalls, slow connection, etc).

**Comment by dygy** [comment]
@rubenlagus it's blocked, as you might know. But if i will get a normal proxy, it would help to escape from webhook error?

**Comment by dygy** [comment]
is it the normal way to set it up? 
public class Main {

 ```
   private static String BOT_NAME = "My test bot";
    private static String BOT_TOKEN = "" /* your bot's token here */;

    private static String PROXY_HOST = "" /* proxy host */;
    private static Integer PROXY_PORT = /* proxy port */;
    private static String PROXY_USER = "" /* proxy user */;
    private static String PROXY_PASSWORD = "" /* proxy password */;

    public static void main(String[] args) {
        try {

            ApiContextInitializer.init();

            // Create the TelegramBotsApi object to register your bots
            TelegramBotsApi botsApi = new TelegramBotsApi();

            // Set up Http proxy
            DefaultBotOptions botOptions = ApiContext.getInstance(DefaultBotOptions.class);

            CredentialsProvider credsProvider = new BasicCredentialsProvider();
            credsProvider.setCredentials(
                    new AuthScope(PROXY_HOST, PROXY_PORT),
                    new UsernamePasswordCredentials(PROXY_USER, PROXY_PASSWORD));

            HttpHost httpHost = new HttpHost(PROXY_HOST, PROXY_PORT);

            RequestConfig requestConfig = RequestConfig.custom().setProxy(httpHost).setAuthenticationEnabled(true).build();
            botOptions.setRequestConfig(requestConfig);
            botOptions.setCredentialsProvider(credsProvider);
            botOptions.setHttpProxy(httpHost);

            botsApi.registerBot((LongPollingBot) new Bot());
        } catch (TelegramApiException e) {
            e.printStackTrace();
        }
    }
}
```

**Comment by dygy** [comment]
okay, last words for this. For everybody who uses long polling bot and also have problems, the situation with constructor I made like this 
```
  protected My_Bot(DefaultBotOptions options) {
        super(options);
```
so creating bot is like this 
`  botsApi.registerBot((LongPollingBot) new IiPPO_Bot(botOptions));`
and it's all working for me. Thx for help @rubenlagus and @bvn13 .

**Comment by TomcatHaodada** [comment]
Hello, do you still have the original code of this problem? I also met the same problem with you, I tried to solve it, but unfortunately I did not solve it. If you still have this code, could you please send it to me?Thank you for your email tomcat.yoyoyo@gmail.com

**Comment by drundanibel** [comment]
I'm facing the same problem right now. My bot and main classes look almost the same as the ones in dygy's first post above.

I get errors like `org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Error removing old webhook [...]` and `Caused by: org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Error deleting webhook: [404] Not Found [...]`

For the moment I would like to realize only a minimal setup: I'm already using my Telegram bot to automatically send (screenshot) messages to different chats with MS PowerShell and curl when our GUI tests fail. I would now like to switch this simple scenario to TelegramBots so that we can gradually equip the bot with more intelligence in the future.

But what is the specific problem with this "old webhook", which I don't need yet, because I don't have to listen to user actions yet?

**Comment by dygy** [comment]
My problem was about connection to telegram servers. So it was because of blocks, and I solve it by these things I wrote before theme get closed. There was also a solution to put a proxy inside System Properties.

I wasn't sure, but old webhook isn't really about reactions for user actions. I had this error too, and it was  different, and it throws only after user trying to get smth from your bot.

**Comment by dygy** [comment]
About System Properties, it wasn't really good solution, because it makes you use proxy from entire project, while you maybe don't need a proxy for you MongoDB, for some other networks working with your bot, etc.

**Comment by kilinochi** [comment]
![image](https://user-images.githubusercontent.com/34065879/55408552-e5179b00-5568-11e9-8ca2-7ad1f773f40e.png)
You can also do this

**Comment by dygy** [comment]
I just wrote it 21 Dec, that this type of solutions not really cool for enterprise. I do not use tor for a long time. In my country it's illegal for proxy businessmens, not for users.

**Comment by kilinochi** [comment]
окей, надеюсь, тут по-русски можно писать, лол
Если честно, я попытался сделать все как ты писал, но у меня почему-то не зашло
Мой метод может и выглядит коряво, но если не выпускать код дальше своего репозитория, то, в принципе, ничего страшного и не будет

**Comment by uPagge** [comment]
@kilinochi тоже пытаюсь сделать как он пишет, нифига не выходит

**Comment by grigory-lobkov** [comment]
@kilinochi Thanks for advice! Now it work's!
Code for copy-past to **main()** method:

        System.getProperties().put("proxySet", "true");

        System.getProperties().put("socksProxyHost", "127.0.0.1");

        System.getProperties().put("socksProxyPort", "9150");

**Comment by Ilya-bmx** [comment]
My Problem fixing is : Write to @BotFather in Telegram and get the token that you need.
