### ISSUE TITLE
java.lang.NoClassDefFoundError when trying to start the bot from a server

### ISSUE THREAD

**Issue by Gonza116** [rubenlagus/TelegramBots#457]
I'm doing a web application using AppEngine and I want to have this Telegram Bot. So, for testing, I tried to use a button that redirects to a Servlet that should start the bots (it calls the main method of the Bot). However, instead of starting, it gives me the following exception:
`Error for /ceusbot
[INFO] java.lang.NoClassDefFoundError: org/apache/http/entity/ContentType
[INFO] 	at org.telegram.telegrambots.bots.DefaultAbsSender.<clinit>(DefaultAbsSender.java:54)
[INFO] 	at ceus.bot.BotMain.startBot(BotMain.java:17)
[INFO] 	at ceus.controller.TelegramBotController.doGet(TelegramBotController.java:29)
[INFO] 	at ceus.controller.TelegramBotController.doPost(TelegramBotController.java:38)
[INFO] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
[INFO] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
[INFO] 	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
[INFO] 	at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:128)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:122)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
[INFO] 	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
[INFO] 	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
[INFO] 	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
[INFO] 	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
[INFO] 	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:95)
[INFO] 	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
[INFO] 	at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:508)
[INFO] 	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
[INFO] 	at org.mortbay.jetty.Server.handle(Server.java:326)
[INFO] 	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
[INFO] 	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
[INFO] 	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
[INFO] 	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
[INFO] 	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
[INFO] 	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
[INFO] 	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
[INFO] Caused by: java.lang.ClassNotFoundException: org.apache.http.entity.ContentType
[INFO] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[INFO] 	at com.google.appengine.tools.development.IsolatedAppClassLoader.loadClass(IsolatedAppClassLoader.java:195)
[INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[INFO] 	... 41 more`.

I'm using maven dependencies, and I've tried with the LongPollingBot and the AbilityBot. So, right now, my pom.xml looks like this:
`<dependencies>
...

		<dependency>
	      <groupId>org.telegram</groupId>
	      <artifactId>telegrambots</artifactId>
	      <version>3.6.1</version>
   		</dependency>
   		
   		<dependency>
	      <groupId>org.telegram</groupId>
	      <artifactId>telegrambots-abilities</artifactId>
	      <version>3.6.1</version>
   		</dependency>
</dependencies>`

If it's any use, here I have the bot itself:
`package ceus.bot;

import org.telegram.abilitybots.api.bot.AbilityBot;
import org.telegram.telegrambots.api.methods.send.SendMessage;
import org.telegram.telegrambots.api.objects.Update;
import org.telegram.telegrambots.exceptions.TelegramApiException;

public class CeusBot extends AbilityBot {
	
	public static String BOT_TOKEN = "586602031:AAHniBeZSWsN_XOiyLiDvRv9FRlsb4ZiaMM";
	public static String BOT_USERNAME = "CEUSbot";

	public CeusBot() {
	    super(BOT_TOKEN, BOT_USERNAME);
	  }
	
	@Override
	public void onUpdateReceived(Update update) {
		if (update.hasMessage() && update.getMessage().hasText()) {
	        SendMessage message = new SendMessage() // Create a SendMessage object with mandatory fields
	                .setChatId(update.getMessage().getChatId())
	                .setText("La prueba ha sido un **EXITO**");
	        try {
	            execute(message); // Call method to send the message
	        } catch (TelegramApiException e) {
	            e.printStackTrace();
	        }
	    }
    }

    @Override
    public String getBotUsername() {
        return BOT_USERNAME;
    }

    @Override
    public String getBotToken() {
        return BOT_TOKEN;
    }
    
    @Override
    public int creatorId() {
      return 1261781;
    }

}`

And the "main method" of the bot:
`package ceus.bot;

import org.telegram.telegrambots.ApiContextInitializer;
import org.telegram.telegrambots.TelegramBotsApi;
import org.telegram.telegrambots.exceptions.TelegramApiException;

public class BotMain {
	public static void startBot() {
		// Initializes dependencies necessary for the base bot - Guice
        ApiContextInitializer.init();

        // Create the TelegramBotsApi object to register your bots
        TelegramBotsApi botsApi = new TelegramBotsApi();

        try {
          // Register your newly created AbilityBot
          botsApi.registerBot(new CeusBot());
        } catch (TelegramApiException e) {
            e.printStackTrace();
        }
    }
}
`
As shown, this is being implemented with the AbilityBot, but I had the same problem with the LongPollingBot. Thanks in advance.

**Comment by rubenlagus** [comment]
Hi, can you try this?

https://stackoverflow.com/questions/9663927/java-lang-noclassdeffounderror-org-apache-http-client-httpclient

**Comment by Gonza116** [comment]
I've added that HttpClient using the Maven dependency. Now I have another error, which seems promising.
`java.security.AccessControlException: access denied ("java.io.FilePermission" "CEUSbot" "write")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at com.google.appengine.tools.development.DevAppServerFactory$CustomSecurityManager.checkPermission(DevAppServerFactory.java:442)
	at java.lang.SecurityManager.checkWrite(SecurityManager.java:979)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:231)
	at org.mapdb.volume.RandomAccessFileVol.<init>(RandomAccessFileVol.java:51)
	at org.mapdb.volume.RandomAccessFileVol$1.makeVolume(RandomAccessFileVol.java:26)
	at org.mapdb.StoreWAL$realVolume$1.invoke(StoreWAL.kt:75)
	at org.mapdb.StoreWAL$realVolume$1.invoke(StoreWAL.kt:18)
	at org.mapdb.StoreWAL.<init>(StoreWAL.kt:74)
	at org.mapdb.StoreWAL$Companion.make(StoreWAL.kt:56)
	at org.mapdb.StoreWAL$Companion.make$default(StoreWAL.kt:55)
	at org.mapdb.DBMaker$Maker.make(DBMaker.kt:464)
	at org.telegram.abilitybots.api.db.MapDBContext.onlineInstance(MapDBContext.java:57)
	at org.telegram.abilitybots.api.bot.AbilityBot.<init>(AbilityBot.java:147)
	at ceus.bot.CeusBot.<init>(CeusBot.java:14)
	at ceus.bot.BotMain.startBot(BotMain.java:17)
	at ceus.controller.TelegramBotController.doGet(TelegramBotController.java:29)
	at ceus.controller.TelegramBotController.doPost(TelegramBotController.java:38)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:128)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:122)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:95)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:508)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)`

Any clue what to do next?

**Comment by rubenlagus** [comment]
It looks like a problem writing to a file, I guess something related to appengine... not sure how permissions works there.

**Comment by MortezaTaghaddomi99** [comment]
> As you said, that's a problem with AppEngine permissions. Seems that they want you to pay to do some things. And this one may be one of them. Thanks anyway!

I have the same problem, could you fix it?

**Comment by Drusilio** [comment]
> > As you said, that's a problem with AppEngine permissions. Seems that they want you to pay to do some things. And this one may be one of them. Thanks anyway!
> 
> I have the same problem, could you fix it?

So Could you fix it?)
