### ISSUE TITLE
EditMessageMedia not working

### ISSUE THREAD

**Issue by tomer953** [rubenlagus/TelegramBots#499]
**Problem:**
 can't edit photo sent by the bot.

**Error shown:**
```
org.telegram.telegrambots.meta.exceptions.TelegramApiException: Unable to edit message media
	at org.telegram.telegrambots.bots.DefaultAbsSender.execute(DefaultAbsSender.java:635)
	at Bot.HandleUpdateMessage(Bot.java:782)
	at Bot.onUpdateReceived(Bot.java:87)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
	at org.telegram.telegrambots.meta.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27)
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:305)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Type id handling not implemented for type org.telegram.telegrambots.meta.api.objects.media.InputMediaVideo (by serializer of type org.telegram.telegrambots.meta.api.objects.media.InputMediaSerializer)
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:284)
.
.
.

```

**steps to reproduce:**
1. send a photo
2. get the message id
3. try to modify that message with new media

sample code that do that:
https://pastebin.com/ebF6QgyT

I tried with:
EditMessageMedia+InputMediaPhoto
EditMessageMedia+InputMediaDocument
EditMessageMedia+InputMediaVideo

all of this produce the same bug.

I did check also: EditMessageReplyMarkup, which works fine. (but not relevant to the result i want)

hope I gave all the details, thanks for your awesome work.

**Comment by tomer953** [comment]
If it helps, I tried to edit it throw the api itself (with POST request), so I think the problem is in the lib...

the POST body that I used is simple as:
```
{
	"chat_id":"404XXXXX",
	"message_id": 1511,
	"media":  { 
		"type": "photo",
		"media":"https://www.mcdonalds.com/content/dam/usa/logo/m_logo.png"
	}
} 
```

I think the java lib is not creating the correct "media" object, maybe something with the "type", but not sure.

please check it out in your spare time, thanks
