### ISSUE TITLE
TelegramApiRequestException: Error getting updates

### ISSUE THREAD

**Issue by aarystan** [rubenlagus/TelegramBots#508]
Everything is working: getting update, sending message.
But in log periodically prints this :
```
ERROR 52828 --- [gram Connection] Telegram Bots Api : BOTSESSION
org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Error getting updates
	at org.telegram.telegrambots.meta.api.methods.updates.GetUpdates.deserializeResponse(GetUpdates.java:119) ~[telegrambots-meta-4.0.1.jar:na]
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.getUpdatesFromServer(DefaultBotSession.java:256) ~[telegrambots-4.0.1.jar:na]
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.run(DefaultBotSession.java:185) ~[telegrambots-4.0.1.jar:na]
```

I have no any ran instances. What's wrong?
```
    public static void main(String[] args) {
        ApiContextInitializer.init();
        TelegramBotsApi botApi = new TelegramBotsApi();
        try {
            botApi.registerBot(new SuperBot());
        } catch (TelegramApiException e) {
            LOGGER.error("TelegramApiException " + e.getMessage(), e);
        }

        SpringApplication.run(Application.class, args);
    }
```
```
    @Override
    public void onUpdateReceived(Update update) {
        // We check if the update has a message and the message has text
        if (update.hasMessage() && update.getMessage().hasText()) {
            SendMessage message = new SendMessage() // Create a SendMessage object with mandatory fields
                    .setChatId(update.getMessage().getChatId())
                    .setText(update.getMessage().getText());
            try {
                execute(message); // Call method to send the message
            } catch (TelegramApiException e) {
                e.printStackTrace();
            }
        }
    }
```

**Comment by sirojovpolot** [comment]
![image](https://user-images.githubusercontent.com/39897332/45816644-b2593400-bcf5-11e8-8f81-352a64c6a654.png)

delete java

**Comment by Bitrons** [comment]
Hi.
Have you find the solution ???
I have same problem, and I don't know how to fix it.

**Comment by Bitrons** [comment]
Hi.
Have you find the solution ???
I have same problem, and I don't know how to fix it.

**Comment by aarystan** [comment]
Oh, i am sorry late response.

I have used Spring Boot and this problem fire when i recompile source code without restart app (with spring-dev-tools)
App tries start new instance of bot when recompile code.
Solution: kill bot instance programmatically or restart app

**Comment by Bitrons** [comment]
@aarystan 
thanks anyway.

**Comment by JavaStream** [comment]
There was such an error when another second copy of this bot was launched.

**Comment by SanzharIo** [comment]
Hi, has anybody solution of this problem?

**Comment by jiaweiloo** [comment]
I tried PreDestroy but can't,

`@Component
public class MyChatBot extends TelegramLongPollingBot {
	@PreDestroy
	public void preDestroy() {
		DefaultBotSession dbs = ApiContext.getInstance(DefaultBotSession.class);
		System.out.println("session: " + dbs.isRunning());
		dbs.stop();
	}`

Anybody have a solution in terminating this ?

**Comment by Chase22** [comment]
@jiaweiloo 
You can inject the bot session by using a method annotated with @AfterBotRegistration and the bot session as a parameter.

The method will be called after the bot got registered and the bot session will be injected into this method

```java
@AfterBotRegistration
public void afterRegistration(BotSession session) {}
```

**Comment by Chijuk** [comment]
Just like @Chase22 wrote: 
inject `BotSession` object with `@AfterBotRegistration` annotation and than you can shoutdown session with its `stop()`  method. Also works in `@PreDestroy` in class with `@AfterBotRegistration` annotation

**Comment by excentro123** [comment]
Hello.
So, all we have to do is something this:
`@AfterBotRegistration
  public void afterRegistration(BotSession session) {
    session.stop();
  }`?

**Comment by Chijuk** [comment]
If your purpose to stop bot right after it start you can do something like that.
Otherwise, for example, you can get `BotSession` object inside `@AfterBotRegistration` and close session later in appropriate way. For example, inside `@PreDestroy`.

**Comment by vokuznetsov** [comment]
I got this error because I registered bot using `@EventListener(ApplicationReadyEvent.class)` annotation. 
When I had changed it to `@PostConstruct` exception disappeared. 

```java
@Slf4j
@Configuration
public class TelegramBotConfig {

    @PostConstruct
    public void start() {
        try {
            log.info("Instantiate Telegram Bots API...");
            TelegramBotsApi botsApi = new TelegramBotsApi(DefaultBotSession.class);

            log.info("Register Telegram Bots API...");
            botsApi.registerBot(new TelegramBot());
        } catch (TelegramApiException e) {
            log.error("Exception instantiate Telegram Bot!", e);
        }
    }
}
```

**Comment by lilhovhann** [comment]
> There was such an error when another second copy of this bot was launched.
You are right

**Comment by Smelly-Foot** [comment]
I FOUND THE SOLUTION!!!!
 TelegramBotsApi telegramBotsApi = new TelegramBotsApi(DefaultBotSession.class);
        try
        {
            var session = telegramBotsApi.registerBot(bot);
            session.stop();
        }

**Comment by Vaisero** [comment]
I FOUND THE SOLUTION!!!!
`TelegramBotsApi telegramBotsApi = new TelegramBotsApi(DefaultBotSession.class);
try
{
var session = telegramBotsApi.registerBot(bot);
**session.stop();**`
