### ISSUE TITLE
bot looses connection (Timeout waiting for connection from pool)

### ISSUE THREAD

**Issue by san3ani** [rubenlagus/TelegramBots#564]
Hello
In versions newer than 3.6, the bot running in many groups always looses connection after hours of working correctly. I start getting the exception 

Caused by: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:292)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:269)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:191)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.telegram.telegrambots.bots.DefaultAbsSender.sendHttpPostRequest(DefaultAbsSender.java:765)
        at org.telegram.telegrambots.bots.DefaultAbsSender.sendMethodRequest(DefaultAbsSender.java:761)
        at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:716)

This does not happen in version 3.6. Any ideas?
Thanks in advanced

**Comment by VinGo91** [comment]
Hello,

I have encountered the same problem a couple of times in the past few weeks. Behavior is exactly the same, my bot is running in a large amount of channels. I too have to restart in order for things to work again.

I get the same error message down to the last line of code.

Have you been able to resolve this issue in the meantime by any chance?

I am using v. 4.2

Thanks!

**Comment by san3ani** [comment]
Hello VinGo91
No I did not find any solution. The only workaround is to use the the old version 3.6
I was thinking that the reason was the HTTP apache library, However, it looks like the 3.6 libraries are the same as the newer versions libraries. So the reason must be with the telegramBot library code.
I am not sue if updating the HTTP apache library will help. I have not tried that.
I was hoping some one here who has deep knowledges in the core code can solve this.

Good luck

**Comment by VinGo91** [comment]
Thanks for the quick reply, I'll try the older version and see how it goes. 

Since this is an issue that only occurs after an uncertain amount of time, it'll probably take a while to know for sure - will report back though.

One thing I noticed is this appears to be happening mostly during high times with an increased amount of incoming updates. My bot is used by people from only a certain timezone, this exclusively occured during times with higher amount of traffic, never at night. I've had it survive a week straight with no hiccups though, so it's really odd.

**Comment by san3ani** [comment]
The same issue appears in the latest api.
It seems I will have to stick with 3.6 version.
Is there a way to update the 3.6 version to the latest update but keep using the old dependencies used in 3.6 Version.

**Comment by rubenlagus** [comment]
Are you using your custom RequestConfig object?

Also, are you using TelegramHttpClientBuilder outside of the API code?

**Comment by san3ani** [comment]
> Are you using your custom RequestConfig object?
> 
> Also, are you using TelegramHttpClientBuilder outside of the API code?
Hello
When the error happened, I did not use any custom configuration and no TelegramHttpClientBuilder outside of the API code.

After the error occurred multiple times, I tried to customize the RequestConfig to change the number of threads options to 5 and it did not help.
Currently I tried the latest version with the following customization
int timeout = 130000;
            SecurityBot bot = new SecurityBot(args[0], args[1]);
            TelegramBotsApi botsApi = new TelegramBotsApi();
            DefaultBotOptions options = bot.getOptions();
            RequestConfig requestConfig = RequestConfig.custom().setConnectTimeout(timeout).setConnectionRequestTimeout(timeout).build();
            options.setMaxThreads(5);
            options.setRequestConfig(requestConfig);


the error is not happening as much as it used to be but I don't know if the above code has to do anything with this since I already kicked my bot from a lot of groups. So there is a big chance that I am not seeing the error due to the less load on the bot.
As VinGo91 mentioned, it only occurs during rush hours of incoming updates and as I mentioned before, when using version 3.6 this error totally disappears.

**Comment by VinGo91** [comment]
Hello,

I would just like to pop in and confirm this again.

Same error and ame behavior is still occuring- on average every 2-3 days.

I have not touched a RequestConfig object and am not using a custom TelegramHttpClientBuilder outside of the API code. (I don't even know what that is.)
