### ISSUE TITLE
SendAnimation still has a problem!

### ISSUE THREAD

**Issue by ShafiqSadat** [rubenlagus/TelegramBots#580]
still i cant send GIF files!

```
Exception in thread " Telegram Executor" java.lang.NoSuchMethodError: ProPosteRobot.execute(Lorg/telegram/telegrambots/meta/api/methods/send/SendAnimation;)Lorg/telegram/telegrambots/meta/api/objects/Message;
        at ProPosteRobot.sendAnimation(ProPosteRobot.java:823)
        at ProPosteRobot.getUpdates(ProPosteRobot.java:261)
        at ProPosJavid.onUpdateReceived(ProPosJavid.java:7)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.telegram.telegrambots.meta.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27)
        at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:305)
```

**Comment by ShafiqSadat** [comment]
Sorry fixed !
