### ISSUE TITLE
java.lang.UnsupportedClassVersionError when launching bot

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [rubenlagus/TelegramBots#7]
I have added `*.jar` file to my NetBeans project as library. I have created java file which extends `TelegramLongPollingBot`. When I launch my main class it throws me this exception:

       java.lang.UnsupportedClassVersionError: org/telegram/telegrambots/TelegramApiException : Unsupported major.minor version 52.0
	     at java.lang.ClassLoader.defineClass1(Native Method)
	     at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
	     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	     at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	     at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	     at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	     at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	     at java.security.AccessController.doPrivileged(Native Method)
	     at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	     at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
   	     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	     at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	     at java.lang.Class.getDeclaredMethods0(Native Method)
	     at java.lang.Class.privateGetDeclaredMethods(Class.java:2451)
	     at java.lang.Class.getMethod0(Class.java:2694)
	     at java.lang.Class.getMethod(Class.java:1622)
	     at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
	     at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
    Exception in thread "main" Java Result: 1

I'm using JDK 1.7

**Comment by flicus** [comment]
Its because this jar file was built with JDK 1.8, you need to use JDK 1.8 or compile your own jar file of the TelegramBots from the sources with JDK 1.7

**Comment by mmohammadi4820** [comment]
Im using JDK 1.8 but , Itsn't change!!!!
why?
