### ISSUE TITLE
httpclient doesn't work for me

### ISSUE THREAD

**Issue by imanih20** [rubenlagus/TelegramBots#746]
i trying to connect with my bot and receive this error and i don't know what to do 
`Exception in thread "main" java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:151)
	at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:977)
	at org.telegram.telegrambots.facilities.TelegramHttpClientBuilder.build(TelegramHttpClientBuilder.java:31)
	at org.telegram.telegrambots.bots.DefaultAbsSender.<init>(DefaultAbsSender.java:79)
	at org.telegram.telegrambots.bots.TelegramLongPollingBot.<init>(TelegramLongPollingBot.java:20)
	at org.telegram.telegrambots.bots.TelegramLongPollingBot.<init>(TelegramLongPollingBot.java:16)`

**Comment by rubenlagus** [comment]
https://stackoverflow.com/questions/37996265/exception-in-thread-main-java-lang-nosuchfielderror-instance
