### ISSUE TITLE
delete forward message

### ISSUE THREAD

**Issue by AndriiRomanenko** [rubenlagus/TelegramBots#815]
Hi. I have some issue when Bot try to delete a forward message.

The logic of my bot is easy. It sends forward messages from private chats (where its super admin)
to the subscribed user (simple interaction with the bot, like private messaging between two users).

In some conditions, I want to delete the forward message, using message id and user chat id. 
When I try to do it - I get an error 

```java
    public void deleteMessage(Long userChatId, Integer messageId) {
        try {
            execute(new DeleteMessage(userChatId, messageId));
        } catch (TelegramApiException e) {
            e.printStackTrace();
        }
    }

org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Error deleting message: [400] Bad Request: message to delete not found
	at org.telegram.telegrambots.meta.api.methods.updatingmessages.DeleteMessage.deserializeResponse(DeleteMessage.java:97)
	at org.telegram.telegrambots.meta.api.methods.updatingmessages.DeleteMessage.deserializeResponse(DeleteMessage.java:28)
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:756)
	at org.telegram.telegrambots.meta.bots.AbsSender.execute(AbsSender.java:56)
	at com.project.service.BotService.deleteMessage(BotService.java:324)
	at com.project.service.BotService.onUpdateReceived(BotService.java:83)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.telegram.telegrambots.meta.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27)
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:321)
```

When I delete the user message - the operation completed successfully.

**Comment by AndriiRomanenko** [comment]
Found solution. I thought that message id of the Bot's message is the same for every user. But I was wrong. When we send the same message to different users (no matter, SendMessage, ForwardMessage) - telegram generates message id depends on the user chat id. It can be checked if we send a forward message to the user. Message id of the bot and message id of the user will differ.
