### ISSUE TITLE
Exception's reason in Kotlin

### ISSUE THREAD

**Issue by KRonst** [rubenlagus/TelegramBots#819]
Hello. I'm using this library with kotlin to create a bot. And I found that any exception doesn't write the reason of this exception.
For test I've created 2 similar bots on java and kotlin to produce same error that must throw an exception (message is too long).

Exception in Java
```
org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Error sending message: [400] Bad Request: message is too long
at org.telegram.telegrambots.meta.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:180)
at org.telegram.telegrambots.meta.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:24)
at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:756)
at org.telegram.telegrambots.meta.bots.AbsSender.execute(AbsSender.java:56)
```

Exception in Kotlin
```
org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Error sending message
at org.telegram.telegrambots.meta.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:180)
at org.telegram.telegrambots.meta.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:24)
at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:756)
at org.telegram.telegrambots.meta.bots.AbsSender.execute(AbsSender.java:56)
```

As you can see the reason of the exception doesn't appear in kotlin. The only way I found is to override all execute methods in my implementation of TelegramLongPollingBot to wrap all calls of **super.execute()** in try-catch block so I can log the real reason of the error.

**Comment by rubenlagus** [comment]
@KRonst Probably some part of the Kotlin default exceptions toString methods? Not familiar with it

In any case, this is how the string is generated: https://github.com/rubenlagus/TelegramBots/blob/547013dcd9d7d8a1f58039c5fede0609c559c757/telegrambots-meta/src/main/java/org/telegram/telegrambots/meta/exceptions/TelegramApiRequestException.java#L88

**Comment by KRonst** [comment]
Okay, looks like I really need to wrap this exceptions. So this issue can be closed :)
