### ISSUE TITLE
Can't implement to Android

### ISSUE THREAD

**Issue by thevercetti** [rubenlagus/TelegramBots#855]
**I follow the instructions and when I run my bot in my android app, I get this error log:**
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.miners.testing, PID: 9496
    java.lang.NoSuchFieldError: No field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar:classes2.dex)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:151)
        at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:977)
        at org.telegram.telegrambots.facilities.TelegramHttpClientBuilder.build(TelegramHttpClientBuilder.java:31)
        at org.telegram.telegrambots.bots.DefaultAbsSender.<init>(DefaultAbsSender.java:83)
        at org.telegram.telegrambots.bots.TelegramLongPollingBot.<init>(TelegramLongPollingBot.java:19)
        at org.telegram.telegrambots.bots.TelegramLongPollingBot.<init>(TelegramLongPollingBot.java:15)
        at com.miners.testing.Bot.<init>(Bot.java:18)
        at com.miners.testing.MainActivity.onCreate(MainActivity.java:111)
        at android.app.Activity.performCreate(Activity.java:6727)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6121)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
W/cr_CrashFileManager: /data/user/0/com.miners.notificationlistener/cache/WebView/Crash Reports does not exist or is not a directory

**Can anyone successfully implemented this library to Android help me?**

**Comment by rubenlagus** [comment]
Looks to be related to the apache dependency ni Android, this library was never intended to be run in Android.
