### ISSUE TITLE
Spring boot 

### ISSUE THREAD

**Issue by slavino** [rubenlagus/TelegramBots#887]
```
org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Error getting updates
	at org.telegram.telegrambots.meta.api.methods.updates.GetUpdates.deserializeResponse(GetUpdates.java:93) ~[telegrambots-meta-5.1.1.jar:na]
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.getUpdatesFromServer(DefaultBotSession.java:263) ~[telegrambots-5.1.1.jar:na]
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.run(DefaultBotSession.java:192) ~[telegrambots-5.1.1.jar:na]
```

jdk1.8.0_241
Windows
Spring Boot 2.4.4

After following the simple steps from https://github.com/rubenlagus/TelegramBots/tree/master/telegrambots-spring-boot-starter the bot is not properly registered.

**Comment by slavino** [comment]
https://github.com/rubenlagus/TelegramBots/issues/892

silly me
