### ISSUE TITLE
Network Issue

### ISSUE THREAD

**Issue by ansidev** [rubenlagus/TelegramBots#890]
I am running my applications using Docker and the application will print the following logs after running a long time.
Rebooting the application does not solve the issue.
Do you know what is the root cause and how to fix this issue? Thank you!

Log:
```java
java.net.UnknownHostException: api.telegram.org
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298) ~[na:na]
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[httpclient-4.5.12.jar!/:4.5.12]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112) ~[httpclient-4.5.12.jar!/:4.5.12]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.12.jar!/:4.5.12]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.12.jar!/:4.5.12]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.12.jar!/:4.5.12]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.12.jar!/:4.5.12]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.12.jar!/:4.5.12]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.12.jar!/:4.5.12]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.12.jar!/:4.5.12]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.12.jar!/:4.5.12]
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.getUpdatesFromServer(DefaultBotSession.java:254) ~[telegrambots-4.9.jar!/:na]
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.run(DefaultBotSession.java:195) ~[telegrambots-4.9.jar!/:na]
```

`build.gradle dependency`

```
implementation group: 'org.telegram', name: 'telegrambots-spring-boot-starter', version: '4.9'
```

**Comment by Chase22** [comment]
That could be a DNS issue. Is the bot running in Russia or China? These are known for blocking connections to telegram, you might have to set a Proxy

**Comment by ansidev** [comment]
> That could be a DNS issue. Is the bot running in Russia or China? These are known for blocking connections to telegram, you might have to set a Proxy

The server is located in Vietnam.

**Comment by lee-qinghua** [comment]
i am in China ,i met the same question ,i tried to change the dns to 8.8.8.8,but it does`t work ,who can help me
